version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: aya
      MYSQL_DATABASE: order
      MYSQL_USER: aya
      MYSQL_PASSWORD: aya
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: