spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: service-product
          uri: lb://product_service #http://localhost:8081 # Adresse de product-service
          predicates:
            - Path=/products/** # Toutes les requêtes vers /products/** redirigées

        - id: service_order
          uri: lb://service_order #http://localhost:8082 # Adresse de order-service
          predicates:
            - Path=/orders/** # Toutes les requêtes vers /orders/** redirigées


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
