spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: aya
    password: aya
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL du serveur Eureka
  instance:
    prefer-ip-address: true # Utilise l'adresse IP pour l'enregistrement

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
